from Globals import WINDOW_WIDTH, WINDOW_HEIGHT
from pyray import Color, Vector2

DEBUG_TITLEBAR_BEGIN_GRADIENT_COLOR = Color(192, 0, 192, 255)
DEBUG_TITLEBAR_END_GRADIENT_COLOR = Color(64, 0, 255, 255)
DEBUG_CLOSE_BUTTON_COLOR = Color(128, 0, 0, 255)
DEBUG_WINDOW_BG_COLOR = Color(32, 32, 32, 255)
WINDOW_BG_COLOR = Color(18, 3, 41, 255)
DEBUG_WINDOW_SIZE = (200, 220)
DEBUG_WINDOW_CLOSE_OFFSET = 20
DEBUG_WINDOW_CLOSE_X_POS = DEBUG_WINDOW_SIZE[0] - DEBUG_WINDOW_CLOSE_OFFSET
debugWindowPos = Vector2(WINDOW_WIDTH - DEBUG_WINDOW_SIZE[0] - 16, 16)
debugContentsHidden = False
draggingWindow = False
memUsageKB = 0
cpuUsage = 0
